version: '3.3'

services:
  app:
    build: .
    image: bot
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - rabbit
    volumes:
      - ./core/repository/db_dump:/app/core/repository/db_dump
      - ./logs:/app/logs
  rabbit:
    image: "rabbitmq:3-management"
    command: rabbitmq-server
    ports:
      - "15672:15672"
      - "5672:5672"
