COMMAND_IS_NOT_FILLED = "<i>Command not specified</i>"
COMMANDS_INFO = "Commands info:"
CONTEXT_CANCEL_MENU = "\n/cancel - Reset current state\n"
UNKNOWN_COMMAND = "Unknown command!"
UNKNOWN_ACTUATOR = "Unknown actuator!"
UNKNOWN_USER = "Unknown user!"
UNKNOWN_COMMAND_OR_ACTUATOR = "Unknown command or you do not have grant for this actuator."
