"""Initial

Revision ID: 3114ee3e308e
Revises: 
Create Date: 2021-03-09 18:38:47.591229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3114ee3e308e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actuator",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actuator_id"), "actuator", ["id"], unique=False)
    op.create_index(op.f("ix_actuator_name"), "actuator", ["name"], unique=True)
    op.create_table(
        "channel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channel_id"), "channel", ["id"], unique=False)
    op.create_index(op.f("ix_channel_name"), "channel", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("telegram_username", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id", "telegram_username", name="uq_id_user"),
        sa.UniqueConstraint("telegram_username"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_telegram_id"), "user", ["telegram_id"], unique=True)
    op.create_table(
        "user_actuator",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("actuator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actuator_id"], ["actuator.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "actuator_id", name="user_actuator_pk"),
    )
    op.create_table(
        "user_channel",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channel.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "channel_id", name="user_channel_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_channel")
    op.drop_table("user_actuator")
    op.drop_index(op.f("ix_user_telegram_id"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_channel_name"), table_name="channel")
    op.drop_index(op.f("ix_channel_id"), table_name="channel")
    op.drop_table("channel")
    op.drop_index(op.f("ix_actuator_name"), table_name="actuator")
    op.drop_index(op.f("ix_actuator_id"), table_name="actuator")
    op.drop_table("actuator")
    # ### end Alembic commands ###
