"""empty message

Revision ID: 379c63f73cf7
Revises: 3114ee3e308e
Create Date: 2021-07-24 16:32:57.084238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379c63f73cf7'
down_revision = '3114ee3e308e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
